@startuml
'https://plantuml.com/sequence-diagram

autonumber
box DeleteStores


->":DeleteStoresCommand": execute(canteens,ui)
activate ":DeleteStoresCommand"
alt canteens.size()>0
    ":DeleteStoresCommand"->"canteens: ArrayList<Canteen>":get(currentCanteenIndex)
    activate "canteens: ArrayList<Canteen>"
    "canteens: ArrayList<Canteen>"-->":DeleteStoresCommand":currentCanteen
    deactivate "canteens: ArrayList<Canteen>"
    ":DeleteStoresCommand"->"ui:Ui":showDisplaySelectStores(currentCanteen)
    activate "ui:Ui"
    "ui:Ui"-->":DeleteStoresCommand"
    deactivate "ui:Ui"
    ":DeleteStoresCommand"->"ui:Ui":readCommand()
    activate "ui:Ui"
    "ui:Ui"-->":DeleteStoresCommand":line
    deactivate "ui:Ui"
    opt line.equals("cancel")
        ":DeleteStoresCommand"->"ui:Ui":showStoreNotDeleted()
        activate "ui:Ui"
        "ui:Ui"-->":DeleteStoresCommand"
        deactivate "ui:Ui"
    end
    ":DeleteStoresCommand"->"currentCanteen:Canteen":getStore(storeIndex)
    activate "currentCanteen:Canteen"
    "currentCanteen:Canteen"-->":DeleteStoresCommand":store
    deactivate "currentCanteen:Canteen"
    ":DeleteStoresCommand"->"store:Store":getStoreName()
    activate "store:Store"
    "store:Store" --> ":DeleteStoresCommand": storeName
    deactivate "store:Store"
    ":DeleteStoresCommand"->"currentCanteen:Canteen":deleteStore(storeIndex)
    activate "currentCanteen:Canteen"
    "currentCanteen:Canteen"-->":DeleteStoresCommand"
    deactivate "currentCanteen:Canteen"
    ":DeleteStoresCommand"->"ui:Ui":showDeleteStore(storeName)
    activate "ui:Ui"
    "ui:Ui"-->":DeleteStoresCommand"
    deactivate "ui:Ui"
    ":DeleteStoresCommand"->"<<class>> \n:UpdateFile":deleteAndUpdateFile()
    activate "<<class>> \n:UpdateFile"
    "<<class>> \n:UpdateFile" -->":DeleteStoresCommand"
    deactivate "<<class>> \n:UpdateFile"
<--":DeleteStoresCommand"
end
deactivate ":DeleteStoresCommand"
@enduml