@startuml
'https://plantuml.com/sequence-diagram

autonumber
box DeleteStores


->":DeleteStoresCommand": execute(canteens,ui)
activate ":DeleteStoresCommand"
    ":DeleteStoresCommand"->":ArrayList<Canteen> canteens":get(currentCanteenIndex)
    activate ":ArrayList<Canteen> canteens"
    ":ArrayList<Canteen> canteens"-->":DeleteStoresCommand":currentCanteen
    deactivate ":ArrayList<Canteen> canteens"
    ":DeleteStoresCommand"->"ui:Ui":showDisplaySelectStores(currentCanteen)
    activate "ui:Ui"
    "ui:Ui"-->":DeleteStoresCommand"
    deactivate "ui:Ui"
    ":DeleteStoresCommand"->"ui:Ui":readCommand()
    activate "ui:Ui"
    "ui:Ui"-->":DeleteStoresCommand":line
    deactivate "ui:Ui"
    alt line.equals("cancel")
        ":DeleteStoresCommand"->"ui:Ui":showStoreNotDeleted()
        activate "ui:Ui"
        "ui:Ui"-->":DeleteStoresCommand"
        deactivate "ui:Ui"
    end
    ":DeleteStoresCommand"->":Canteen":getStore(storeIndex)
    activate ":Canteen"
    ":Canteen"-->":DeleteStoresCommand":store
    deactivate ":Canteen"
    ":DeleteStoresCommand"->":Store":getStoreName()
    activate ":Store"
    ":Store" --> ":DeleteStoresCommand": storeName
    deactivate ":Store"
    ":DeleteStoresCommand"->":Canteen":deleteStore(storeIndex)
    activate ":Canteen"
    ":Canteen"-->":DeleteStoresCommand"
    deactivate ":Canteen"
    ":DeleteStoresCommand"->"ui:Ui":showDeleteStore(storeName)
    activate "ui:Ui"
    "ui:Ui"-->":DeleteStoresCommand"
    deactivate "ui:Ui"
    ":DeleteStoresCommand"->"<<class>> \n:UpdateFile":deleteAndUpdateFile()
    activate "<<class>> \n:UpdateFile"
    "<<class>> \n:UpdateFile" -->":DeleteStoresCommand"
    deactivate "<<class>> \n:UpdateFile"
<--":DeleteStoresCommand"
deactivate ":DeleteStoresCommand"
@enduml