@startuml
'https://plantuml.com/sequence-diagram

autonumber
box DeleteReviews

->":DeleteReviewsCommand": execute(canteens,ui)
activate ":DeleteReviewsCommand"
alt canteens.size()>0
    ":DeleteReviewsCommand"->"canteens: ArrayList<Canteen>":get(currentCanteenIndex)
    activate "canteens: ArrayList<Canteen>"
    "canteens: ArrayList<Canteen>"-->":DeleteReviewsCommand":currentCanteen
    deactivate "canteens: ArrayList<Canteen>"
    ":DeleteReviewsCommand"->"store:Store":getStore(currentStoreIndex)
    activate "store:Store"
    "store:Store"-->":DeleteReviewsCommand":store
    deactivate "store:Store"
    ":DeleteReviewsCommand"->"store:Store":getReviews()
    activate "store:Store"
    "store:Store"-->":DeleteReviewsCommand":reviews
    deactivate "store:Store"
    ":DeleteReviewsCommand"->"store:Store":getAverageRating()
    activate "store:Store"
    "store:Store"-->":DeleteReviewsCommand":averageRating
    deactivate "store:Store"
    ":DeleteReviewsCommand"->"store:Store":getStoreName()
    activate "store:Store"
    "store:Store"-->":DeleteReviewsCommand":storeName
    deactivate "store:Store"
    ":DeleteReviewsCommand"->"ui:Ui":showReviews(storeName, reviews,averageRating)
    activate "ui:Ui"
    "ui:Ui"-->":DeleteReviewsCommand"
    deactivate "ui:Ui"
    ":DeleteReviewsCommand"->"ui:Ui":showDeleteReview()
    activate "ui:Ui"
    "ui:Ui"-->":DeleteReviewsCommand"
    deactivate "ui:Ui"
    ":DeleteReviewsCommand"->"ui:Ui":readCommand()
    activate "ui:Ui"
    "ui:Ui"-->":DeleteReviewsCommand":line
    deactivate "ui:Ui"
    opt line.equals("cancel")
    ":DeleteReviewsCommand"->"ui:Ui":showReviewNotDeleted
    activate "ui:Ui"
    "ui:Ui"-->":DeleteReviewsCommand"
    deactivate "ui:Ui"
    end
    ":DeleteReviewsCommand"->"store:Store":deleteReview(reviewIndex)
    activate "store:Store"
    "store:Store"-->":DeleteReviewsCommand"
    deactivate "store:Store"
    ":DeleteReviewsCommand"->"ui:Ui":reviewDeleted()
    activate "ui:Ui"
    "ui:Ui"-->":DeleteReviewsCommand"
    deactivate "ui:Ui"
    ":DeleteReviewsCommand"->"<<class>> \n:UpdateFile":deleteAndUpdateFile()
    activate "<<class>> \n:UpdateFile"
    "<<class>> \n:UpdateFile"-->":DeleteReviewsCommand"
    deactivate "<<class>> \n:UpdateFile"
    <--":DeleteReviewsCommand"
end
deactivate ":DeleteReviewsCommand"
@enduml