@startuml
'https://plantuml.com/sequence-diagram

autonumber
box ReadReviews


->":ReadReviewsCommand": execute(canteens,ui)
activate ":ReadReviewsCommand"
":ReadReviewsCommand"->"store:Store":getReviews()
activate "store:Store"
"store:Store"-->":ReadReviewsCommand":reviews
deactivate "store:Store"
opt reviews.size()>0
    ":ReadReviewsCommand"->"store:Store":getAverageRating()
    activate "store:Store"
    "store:Store"-->":ReadReviewsCommand":averageRating
    deactivate "store:Store"
    ":ReadReviewsCommand"->"store:Store":getStoreName()
    activate "store:Store"
    return storeName
    deactivate "store:Store"
    ":ReadReviewsCommand"->"ui:Ui":showReviews(storeName,reviews,averageRating)
    activate "ui:Ui"
    "ui:Ui"-->":ReadReviewsCommand"
     deactivate "ui:Ui"
    <--":ReadReviewsCommand"
end
deactivate ":ReadReviewsCommand"

@enduml